version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    # Ignore ALL major version updates to prevent breaking code changes automatically
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    
    # Specific groups to keep things tidy
    groups:
      dependencies:
        patterns:
          - "*"
