-- Create Artworks Table
create table public.artworks (
  id uuid default gen_random_uuid() primary key,
  title text not null,
  category text check (category in ('fan_art', 'religious', 'personal')),
  image_url text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Availability Table
create table public.availability (
  id int primary key generated by default as identity,
  is_accepting_commissions boolean default true
);

-- Seed Availability (One row only)
insert into public.availability (id, is_accepting_commissions) values (1, true);

-- Create Referrals Table
create table public.referrals (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  email text not null,
  referral_code text unique not null,
  is_used boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Commissions Table
create table public.commissions (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  email text not null,
  phone text,
  instagram_id text,
  size text not null,
  number_of_people int not null default 1,
  background_detail text,
  address text not null,
  notes text,
  status text check (status in ('pending', 'accepted', 'completed')) default 'pending',
  referral_code text references public.referrals(code),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.artworks enable row level security;
alter table public.availability enable row level security;
alter table public.commissions enable row level security;
alter table public.referrals enable row level security;

-- Policies
create policy "Public artworks are viewable by everyone"
  on public.artworks for select
  using ( true );

create policy "Public availability is viewable by everyone"
  on public.availability for select
  using ( true );

create policy "Anyone can submit a commission"
  on public.commissions for insert
  with check ( true );

create policy "Anyone can validate referral code"
  on public.referrals for select
  using ( true );
